builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
    - linux
  goarch:
    - amd64
dockers:
  - image_templates:
    - "errm/mysql-count-exporter:{{.Version}}"
archive:
  replacements:
    linux: Linux
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
